### ISSUE TITLE
New update for fulfillment inbound

### ISSUE THREAD

**Issue by Javadebi** [ScaleLeap/selling-partner-api-sdk#1021]
Hello, there is a [new version](https://developer-docs.amazon.com/sp-api/docs/fulfillment-inbound-api-v2024-03-20-reference#overview) for inbound fulfillment. I was hoping you could add it to your awesome package.

**Comment by moltar** [comment]
Should be automatically created, but we have some failures in the process. Once that is fixed (#1022) then the models will be released. Wait a day or two, please.

**Comment by Javadebi** [comment]
> Should be automatically created, but we have some failures in the process. Once that is fixed (#1022) then the models will be released. Wait a day or two, please.

Thank you so much, appreciate your job 🙏🙏🙏
