### ISSUE TITLE
Can you provide a more detailed document?

### ISSUE THREAD

**Issue by jiangdi0924** [ScaleLeap/selling-partner-api-sdk#133]

**Comment by jiangdi0924** [comment]
i have a bit trouble about aws4-axios

**Comment by moltar** [comment]
Hi @jiangdi0924,

You'll need to provide a bit more context for us to be able to help you.

The `aws4-axios` package is an implementation detail that isn't exposed to the consumer, so we don't document it.

**Comment by jiangdi0924** [comment]
@moltar  thanks for reply my question is  `auth denied `, params was correctly

`        {
          message: 'Access to requested resource is denied.',
          code: 'Unauthorized',
          details: ''
        }`

    axios.interceptors.request.use(
        aws4Interceptor(
            { 
                region: "us-east-1", 
                service: "execute-api" ,
                assumeRoleArn: 'arn:aws:iam::XXXXXXXX:role/spapi-role',
                assumedRoleExpirationMarginSec: 1000,
                signQuery: false
            },
            {
                accessKeyId: "AKIXXXXXXXN",
                secretAccessKey: "XXXXXXXXX",
            }
        )
     );

    let { data }  = await axios.get("https://sellingpartnerapi-na.amazon.com/catalog/2021-06-01")
    `

**Comment by moltar** [comment]
@jiangdi0924 if you are using `axios` and `aws4-axios` directly, then it has nothing to do with this package.
