### ISSUE TITLE
RDT for getOrders and getOrderItems

### ISSUE THREAD

**Issue by optikalefx** [ScaleLeap/selling-partner-api-sdk#327]
Hi folks,

The API is recommending that these calls use the RDT. Is using the RDT something that this sdk handles or is that something that the developer has to implement on top of this sdk?

Thanks!

**Comment by moltar** [comment]
This package does not handle auth, only the access patterns to SP API. Thereby you can [supply your RDT as per normal](https://github.com/ScaleLeap/selling-partner-api-sdk#basic-usage) via the `accessToken` property.

I personally have not tested this, but [according to the docs](https://github.com/amzn/selling-partner-api-docs/blob/main/guides/en-US/use-case-guides/tokens-api-use-case-guide/tokens-API-use-case-guide-2021-03-01.md#step-3-include-the-rdt-with-a-call-to-the-getorderitems-operation), this should work.

**Comment by moltar** [comment]
I am going to close the issue, but if this isn't yet solved, please feel free to let me know and I'll reopen it.

**Comment by optikalefx** [comment]
Thanks! Just making sure. Yea it's convoluted, but it does in fact work.

**Comment by moltar** [comment]
SP API indeed is the most convoluted API I had the "pleasure" to deal with :)
