### ISSUE TITLE
GetTransportContent MWS returning a IN instead inches

### ISSUE THREAD

**Issue by armgoja** [ScaleLeap/selling-partner-api-sdk#334]
Hi,

I am having the following issue getting transport content information, anyone having the same issue ?

"stack":"ParsingError: Problem with the value of property \"GetTransportContentResponse\": Problem with the value of property \"GetTransportContentResult\": Problem with the value of property \"TransportContent\": Problem with the value of property \"TransportDetails\": Problem with the value of property \"PartneredSmallParcelData\": One of the following problems occured: (0) Problem with the value of property \"PackageList\": Problem with the value at index 0: Problem with the value of property \"Dimensions\": Problem with the value of property \"Unit\": Expected an enum member, but received a string with value \"IN\", (1) Expected an undefined, but received an object with value

**Comment by moltar** [comment]
I think you opened the issue in the wrong repo.

Did you mean to open in https://github.com/ScaleLeap/amazon-mws-api-sdk ?
