### ISSUE TITLE
feature-request: make error interceptor optional

### ISSUE THREAD

**Issue by xiaoyu-tamu** [ScaleLeap/selling-partner-api-sdk#478]
It would be nice you can make error interceptor optional if user pass custom axios instance.

```ts
if (axios) {
  axiosInstance = axios
} else {
  // move error interceptors into else block
}
```

**Comment by moltar** [comment]
> It would be nice you can make error interceptor optional if user pass custom axios instance.

What's the use case?

**Comment by xiaoyu-tamu** [comment]
I need to access the `error.config` from axios error in error interceptor, there is no way to do that since this lib throw custom error without the original error info.

```
api.http.interceptors.response.use(
      (res) => res,
      async (error) => {
        if (!axios.isAxiosError(error) || !error.response) throw error;

        // custom logic before retry

        delete error.config.headers?.['X-Amz-Security-Token'];
        delete error.config.headers?.['X-Amz-Date'];
        delete error.config.headers?.['Authorization'];
        return api.http.request(error.config);
      }
    );
```

or maybe we can use error#cause to do that?

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error/cause

**Comment by moltar** [comment]
> Alternative, maybe this lib can include the original error in error#cause?

Yeah, I think this is the right approach IMO.

**Comment by moltar** [comment]
@xiaoyu-tamu do you want to contribute a PR?
