### ISSUE TITLE
Which version of the API is used?

### ISSUE THREAD

**Issue by smargoli2** [ScaleLeap/selling-partner-api-sdk#531]
Hey,
How do you determine which version of the API to use? For example, the Catalog items API has 3 versions. Do you just pull the latest one? How do know if a new one was released?
I'm asking because we're generating C# code from the models using swagger codegen but we're coming up against this issue.

**Comment by moltar** [comment]
We generate all models.

See:

https://github.com/ScaleLeap/selling-partner-api-sdk/tree/master/src/api-models

![screenshot-20220824T111157-08nzXRs7](https://user-images.githubusercontent.com/491247/186392764-a37db134-332a-479e-bb5d-1e6bd2831fb6.png)

https://github.com/ScaleLeap/selling-partner-api-sdk/tree/master/src/api-clients

![screenshot-20220824T111212-BsfpCo1U](https://user-images.githubusercontent.com/491247/186392851-58ff5dc2-982c-402a-a797-39d4279c93a0.png)

---

https://github.com/ScaleLeap/selling-partner-api-sdk/blob/35f0a3715e0c3f898795385ded598ced97ba62ed/utils/generate.ts#L29-L33

**Comment by moltar** [comment]
I'm going to close the issue, as it's not really an issue. But feel free to continue the discussion.

**Comment by smargoli2** [comment]
Thanks :) You need a discussion tab!
How do you keep track of new releases from Amazon's side?

**Comment by moltar** [comment]
> Thanks :) You need a discussion tab!

If we get more discussions we can add one. For now this is ok too.

>  How do you keep track of new releases from Amazon's side?

https://github.com/ScaleLeap/selling-partner-api-sdk/blob/35f0a3715e0c3f898795385ded598ced97ba62ed/.github/workflows/generate-models.yml#L3-L6

**Comment by smargoli2** [comment]
If we're starting anew project now, should we just take the latest version of each model?

**Comment by moltar** [comment]
Yes, especially the reports, as the older versions have convoluted report encryption for no reason. Also, older versions do get deprecated.

**Comment by smargoli2** [comment]
Okay thanks! What do you do about models that are used by more than one model? For example, the PartyIdentification model is used by quite a few of the Apis. How do you structure the code base?
