### ISSUE TITLE
FbaInventoryApiClient.getInventorySummaries()

### ISSUE THREAD

**Issue by froyoga** [ScaleLeap/selling-partner-api-sdk#539]
I'm trying to call `getInventorySummaries()` but am unsure what to pass in for the `granularityType` parameter. I tried to set it as type Marketplace but get this error:

```
Type 'Marketplace' is not assignable to type '"Marketplace"'.
```

Do you have any examples of how to call `getInventorySummaries()`?

**Comment by froyoga** [comment]
https://github.com/ScaleLeap/selling-partner-api-sdk/blob/8ba4a56484bfcd06d7344c9f2a3aa99f47635b22/src/api-models/fba-inventory-api-model/api.ts#L502

It works if I replace the above line with `readonly granularityType: string;`, based on what I'm seeing in the [SP API docs](https://developer-docs.amazon.com/sp-api/docs/fbainventory-api-v1-reference#getinventorysummaries:~:text=Schema-,granularityType,-optional).

And the [Use Case Guide](https://developer-docs.amazon.com/sp-api/docs/fba-inventory-api-v1-use-case-guide#:~:text=summaries%3Fdetails%3Dtrue%26-,granularityType%3DMarketplace,-%26granularityId%3DATVPDKIKX0DER%26marketplaceIds) also defines that parameter as just a string value: "Marketplace":

```
GET https://sellingpartnerapi-na.amazon.com/fba/inventory/v1/summaries?details=true&granularityType=Marketplace&granularityId=ATVPDKIKX0DER&marketplaceIds=ATVPDKIKX0DER
```

**Comment by nguyentoanit** [comment]
@froyoga : I didn't see any compilation error here. 🤔 

```ts
      const client = new FbaInventoryApiClient(apiConfigurationParameters)

      client.getInventorySummaries({
        granularityType: 'Marketplace',
        granularityId: 'YOUR_GRANULARITY_ID',
        marketplaceIds: ['ATVPDKIKX0DER'],
      })
```

**Comment by froyoga** [comment]
Interesting, if I do it the way you did it then it works. But if I set the params in a const first, I get the compilation error:

```js
const client = new FbaInventoryApiClient(apiConfigurationParameters)
const params = {
        granularityType: 'Marketplace',
        granularityId: 'YOUR_GRANULARITY_ID',
        marketplaceIds: ['ATVPDKIKX0DER'],
      }

client.getInventorySummaries(params)
```

**Comment by nguyentoanit** [comment]
As I know, 

> A string literal type can be considered a subtype of the string type. This means that a string literal type is assignable to a plain string, but not vice-versa.

See [this PR](https://github.com/Microsoft/TypeScript/pull/5185).

If you want to create a `params`, you can define a type for them.

```ts
      const client = new FbaInventoryApiClient(apiConfigurationParameters)
      const parameter: FbaInventoryApiGetInventorySummariesRequest = {
        granularityType: 'Marketplace',
        granularityId: 'YOUR_GRANULARITY_ID',
        marketplaceIds: ['ATVPDKIKX0DER'],
      }

      client.getInventorySummaries(parameter)
```

**Comment by froyoga** [comment]
Ah okay, that makes sense. Thanks!
