### ISSUE TITLE
Using Shipping API v2

### ISSUE THREAD

**Issue by Antonio0001999** [ScaleLeap/selling-partner-api-sdk#564]
Hello. This library is the closest I have been to make Amazon's Shipping API work, but the ShippingAPIClient class only allows to make calls to Shipping API v1, would it be possible to make it work for Shipping API v2?

Many thanks.

**Comment by moltar** [comment]
Could you please point to the docs for the source?

@nguyentoanit Please add this, if we are indeed missing this model.

**Comment by Antonio0001999** [comment]
The Shipping API v2 I'm talking about is at https://developer-docs.amazon.com/amazon-shipping/docs/shipping-api-v2-reference

This is the docs I tried to follow, is it part of the same API or I'm confused? Any help on this would be helpful, thanks.

**Comment by nguyentoanit** [comment]
@Antonio0001999 :
They only added them into documentation site, not model repository.

We were using models from [API model's repo](https://github.com/amzn/selling-partner-api-models) to generate classes automatically.
Therefore, we cannot make a call to Shipping API v2 from this SDK so far.

Also, I opened [an issue](https://github.com/amzn/selling-partner-api-models/issues/274) to ask them about this.

**Comment by Antonio0001999** [comment]
Many thanks for your time. Please, let me know if you are able to add it in the future.

**Comment by nguyentoanit** [comment]
@moltar : Should we generate API models from external sources?
Like this Shipping API v2 model?

**Comment by moltar** [comment]
> Should we generate API models from external sources?

Let's hold off and see what they reply in the issue you created.

@Antonio0001999 Please :+1: the issue @nguyentoanit created to give it more juice 😁

**Comment by optikalefx** [comment]
@Antonio0001999 We implemented v2 shipping about a year ago. We also made a bunch of selling partner helpers for reports and feeds in our fork. https://github.com/whitebox-co/selling-partner-api-sdk

**Comment by optikalefx** [comment]
And @moltar @nguyentoanit the OpenAPI Spec is here https://github.com/whitebox-co/selling-partner-api-sdk/blob/master/models/shipping-api-model-v2/shippingV2.json
