### ISSUE TITLE
[Bug] financial api has wrong name.

### ISSUE THREAD

**Issue by xiaoyu-tamu** [ScaleLeap/selling-partner-api-sdk#61]
https://github.com/ScaleLeap/selling-partner-api-sdk/blob/master/src/api-models/finances-api-model/api.ts#L2152

not sure why it mapped to `DefaultApi`, it should be `FinancesApi`

**Comment by nguyentoanit** [comment]
@xiaoyu-tamu : 
There was no official document about API class names that I could find.
But when I try to add `tags` in [financial specification](https://github.com/amzn/selling-partner-api-models/blob/main/models/finances-api-model/financesV0.json). It works great.

At the moment, we're using [OpenAPI Generator](https://openapi-generator.tech/) to generate `typescript-axios` client.

Therefore, I opened the issues to [add tags into specification](https://github.com/amzn/selling-partner-api-models/issues/88)
and confirm about [using tags for API class name in generator](https://github.com/OpenAPITools/openapi-generator/issues/9237).

Thanks.

**Comment by moltar** [comment]
@nguyentoanit was this fixed today with #78 & #79?

**Comment by nguyentoanit** [comment]
@xiaoyu-tamu:
We have created an additional layer that wraps the generated code into something more user friendly.
You can use `FinancesApiClient` replace for `DefaultApi`  in [v3.0.0](https://github.com/ScaleLeap/selling-partner-api-sdk/releases/tag/v3.0.0)

**Comment by nguyentoanit** [comment]
@moltar : I think this was fixed completely. Because specification still mapped to `DefaultApi`
But users can use our additional layers as a replacement.
