### ISSUE TITLE
Is it convenient to export the code in the helper directory

### ISSUE THREAD

**Issue by hoist1999** [ScaleLeap/selling-partner-api-sdk#734]
I have a need to let axios make requests through a network proxy, so I want to call the code in the helper directory for configuration. thank you.

**Comment by moltar** [comment]
You can already do that by passing an `axios` instance to the client constructor.

```ts
import { NotificationsApiClient } from '@scaleleap/selling-partner-api-sdk'
import axios from 'axios'

new NotificationsApiClient({
  basePath,
  axios: axios.create({
    // ... create axios however you want
  }),
})
```

**Comment by hoist1999** [comment]
Thank you very much for your reply. I know that the instance of axios can be passed to the API in this way, but there is a troublesome place in this way, that is, I cannot re-code the logic of ApiClientHelpers. In other words, in order to set up the network proxy, I have to completely re-customize an axios instance, and I have to reconfigure the interceptors.

Is it possible to add network proxy configuration to the interface, for example as follows:
thanks.

`
export const ApiClientHelpers = {
  getAxiosInstance(parameters: APIConfigurationParameters): AxiosInstance {
    let axiosInstance: AxiosInstance;
    const { axios } = parameters;

    if (axios) {
      axiosInstance = axios;
    } else {
      const { accessToken, credentials, region, roleArn } =
        ApiClientHelpers.validateRegion(parameters);

      const config: AxiosRequestConfig = {
        headers: {
          "user-agent": USER_AGENT,
          "x-amz-access-token": accessToken ?? "",
        },
      };

      if (parameters.proxy) {
        // add proxy here
        let httpsAgent = new SocksProxyAgent(parameters.proxy);
        let httpAgent = httpsAgent;
        config.httpAgent = httpAgent;
        config.httpsAgent = httpsAgent;
      }

      axiosInstance = globalAxios.create(config);

      axiosInstance.interceptors.request.use(
        aws4Interceptor(
          {
            region,
            service: "execute-api",
            assumeRoleArn: roleArn,
          },
          credentials
        )
      );
    }

    axiosInstance.interceptors.response.use(
      (response: AxiosResponse) => response,
      (error: AxiosError) => {
        throw apiErrorFactory(error);
      }
    );

    return axiosInstance;
  },

`

**Comment by moltar** [comment]
Also, the solution we use, is simply to set the `basePath` to an endpoint, which then proxies to the SP API endpoint. 

Effectively, it is the same thing.

You can use something like this: https://github.com/http-party/node-http-proxy

Our proxy also does the AWS4 signing.
