### ISSUE TITLE
revert report api to 2020-09-04

### ISSUE THREAD

**Issue by xiaoyu-tamu** [ScaleLeap/selling-partner-api-sdk#74]
After upgrade to v2, getting 403 status for report api.

Looks like the newer version is not ready to use

see https://github.com/amzn/selling-partner-api-docs/issues/646#issuecomment-825232385

also see

> These resources provide preview information about the new version of the Reports and Feeds API that will be released in Summer 2021 to help you create or adjust integrations that do not require client-side encryption for reports or feeds as you migrate to SP-API:

https://github.com/amzn/selling-partner-api-docs/issues/563

**Comment by moltar** [comment]
@xiaoyu-tamu yes, this is being reverted already. Should be released shortly.

**Comment by xiaoyu-tamu** [comment]
@nguyentoanit @moltar 

I just realized this PR also revert catalogItems_2020-12-01 to catalogItems_v0

I guess the catalogItems_2020-12-01 version is stable since 2020-12-01.


if the file postfix date is in the future, we should consider it as preview version. otherwise, consider as stable?

e.g.
```
catalogItems_2020-12-01.md should consider as stable because the version date is in the past
reports_2021-06-30.md should consider as preview because the version date is in the future
```


https://github.com/ScaleLeap/selling-partner-api-sdk/blob/2792525624f18f61e6c9764cf663966fd1ce561b/gulpfile.ts#L310-L321

**Comment by moltar** [comment]
@xiaoyu-tamu good point!

Although I don't think we got a definitive answer from SP API team about the deprecation and when the new endpoints go into effect.

I wonder if it is safe to assume that once the date cuts off, then we should upgrade to that endpoint?

Maybe this should be done manually. Because some of these changes can also be breaking. In which case it might be better to group them into one release.

But I also want to balance it with a burden of having to do anything manual here.

Thoughts?

**Comment by xiaoyu-tamu** [comment]
you are right, include them manually is much safer.

Or maybe we could generate all api versions and let developer choose which one they want to use.

e.g.
```

The amazon doc folder structure
catalogItemsV0.md
catalogItems_2020-12-01.md

// catalogItemsV0.md The first file is always default
class CatalogItemsApiClient {}

// catalogItems_2020-12-01.md
class CatalogItemsApiClient2020_12_01 {}

// catalogItems_2021-06-01.md assume there is another one
class CatalogItemsApiClient2021_06_01 {}
```

Also there is no breaking changes unless amazon remove the the legacy api

**Comment by moltar** [comment]
> Or maybe we could generate all api versions and let developer choose which one they want to use.

Hm, that's also a good idea!

@nguyentoanit thoughts?

**Comment by nguyentoanit** [comment]
I think that's a good idea as well. Will do them in the next release. 👍

**Comment by moltar** [comment]
> I think that's a good idea as well. Will do them in the next release. 👍

Let's not use underscores in the names, but other than that ok :)

**Comment by nguyentoanit** [comment]
> > I think that's a good idea as well. Will do them in the next release. 👍
> 
> Let's not use underscores in the names, but other than that ok :)

May be `CatalogItemsApiClientV20210601`?

**Comment by moltar** [comment]
Ok, but what if it's `V0`? Will it be `VV0` then?

**Comment by moltar** [comment]
Also will need to document this, otherwise noone will be able to find these classes.

Maybe use typedoc to generate something at least?

**Comment by nguyentoanit** [comment]
> Ok, but what if it's `V0`? Will it be `VV0` then?

I don't think they have any release before V0 version. Therefore, V0 will be generated as default name (`CatalogItemsApiClient`).

**Comment by nguyentoanit** [comment]
@xiaoyu-tamu : All API versions were supported in [v3.6.0](https://github.com/ScaleLeap/selling-partner-api-sdk/releases/tag/v3.6.0). 🚀 

Generated docs: https://selling-partner-api-sdk.scaleleap.org
