### ISSUE TITLE
Any plan to support vendor api in `selling-partner-api-sdk`?

### ISSUE THREAD

**Issue by xiaoyu-tamu** [ScaleLeap/selling-partner-api-sdk#83]
Hi, Looks like amazon added vendor models today,

![image](https://user-images.githubusercontent.com/33362998/116608049-5963ca80-a8f8-11eb-9958-7c6c04a6495f.png)

Will this repo support vendor related api or it will be a separate repo?

**Comment by moltar** [comment]
It will support all models available in the repo.

The idea was to generate them automatically on schedule. But it might not be working correctly yet.
