### ISSUE TITLE
Fix for api-client-helpers.js file

### ISSUE THREAD

**Issue by skaraudio** [ScaleLeap/selling-partner-api-sdk#845]
Please implement on lines 33-40. Didn't have time to put something more official together but will fix the error that is currently getting thrown.

I've added the content-type here Amazon requires.

```
const { accessToken, credentials, region, roleArn } = exports.ApiClientHelpers.validateRegion(parameters);
			axiosInstance = axios_1.default.create({
				headers: {
					"user-agent": constants_1.USER_AGENT,
					"x-amz-access-token": accessToken !== null && accessToken !== void 0 ? accessToken : "",
					"Content-Type": "application/json; charset=utf-8",
				},
			});
```

**Comment by moltar** [comment]
> but will fix the error that is currently getting thrown.

What error is that?

Note that all of the code is auto-generated from OpenAPI specs.

**Comment by skaraudio** [comment]
I was getting a content type error so I manually edited this file: 

![image](https://github.com/ScaleLeap/selling-partner-api-sdk/assets/15099697/d52036a0-c02e-495f-816b-e34daa1d3d09)

**Comment by moltar** [comment]
Could you please share the entire error? I am curious to see what it was. Maybe we do need to fix something.

Btw, unless you use a patching mechanism, e.g. `patch-packge` or pnpm's built-in feature, then the next time you install the package(s), your manual change will be reset.
