### ISSUE TITLE
Unsafe headers

### ISSUE THREAD

**Issue by afuentesdp90** [ScaleLeap/selling-partner-api-sdk#852]
![Captura de pantalla 2023-07-10 a las 12 59 35](https://github.com/ScaleLeap/selling-partner-api-sdk/assets/45896400/323c6fc1-4cfb-44d5-a058-bdb11ae5051b)

Hi all!

I follow the steps and appear the "Unsafe headers". It seems like a CORS error but I don't know how to solve this.

Any idea? Thanks :)

**Comment by moltar** [comment]
Hi @afuentesdp90, this package is not designed to be used in the browser. Although I do not see why it wouldn't work. However, a CORS issue is not something we can help solve as it is controlled by the server. Also, in addition, you can take full control of the user agent (axios instance), and then we _really_ have nothing to do with the transport layer, so you get full control.
