### ISSUE TITLE
Sandbox not working

### ISSUE THREAD

**Issue by jesusvalle** [ScaleLeap/selling-partner-api-sdk#91]
Good morning,

I see that since a couple of versions ago the isSandbox parameter is no longer present.

I used to make requests in sandbox mode by passing to the configuration parameters the basePath: 'https://sandbox.sellingpartnerapi-eu.amazon.com', but since version 3, using this path returns me the error SellingPartnerInternalServerError. 

Any suggestions please?

Thank you very much.

**Comment by moltar** [comment]
@jesusvalle please share a code sample

**Comment by jesusvalle** [comment]
This is my configuration parameters

```
CONFIGURATION:  {
  accessToken: 'Atza|XXXXXXXXXXXX', // generated calling https://api.amazon.com/auth/o2/token endpoint
  region: 'eu-west-1',
  basePath: 'https://sandbox.sellingpartnerapi-eu.amazon.com',
  credentials: { // Generated by sts call
    accessKeyId: 'XXXXXXXXXXXXXX',
    secretAccessKey: 'XXXXXXXXXXXXXXXXXXXX',
    sessionToken: 'XXXXXXXXXXXXXXXXX'
  },
  roleArn: 'arn:aws:iam::XXXXXXXXX:role/SellingPartnerAPIRol'
}
```

And this is my call:

```
const catalog = new CatalogItemsApiClient(configuration);
const item = await catalog.getCatalogItem({
    asin: 'XXXXXXXXXX',
    marketplaceId: es.id, //A1RKKUPIHCS9HS
});```

**Comment by nguyentoanit** [comment]
@jesusvalle: 
There is the docs describe "[How to make a sandbox call to the Selling Partner API](https://github.com/amzn/selling-partner-api-docs/blob/main/guides/en-US/developer-guide/SellingPartnerApiDeveloperGuide.md#how-to-make-a-sandbox-call-to-the-selling-partner-api)"

I could reproduce your issue when using `getCatalogItem` method.
But followed them and resolved similar error for `getReports` in `ReportsApiClient`.

**Comment by jesusvalle** [comment]
> @jesusvalle:
> There is the docs describe "[How to make a sandbox call to the Selling Partner API](https://github.com/amzn/selling-partner-api-docs/blob/main/guides/en-US/developer-guide/SellingPartnerApiDeveloperGuide.md#how-to-make-a-sandbox-call-to-the-selling-partner-api)"
> 
> I could reproduce your issue when using `getCatalogItem` method.
> But followed them and resolved similar error for `getReports` in `ReportsApiClient`.

I checked the getCatalogItem call with the documentation and I saw that it was not necessary to send any special parameter. I made a test request without sending parameters (forcing any type) but it also gives error.

Any news about this? Thank you very much

**Comment by moltar** [comment]
@jesusvalle we generate the types from the models provided by Amazon. Sometimes they have errors, but you need to raise that in the models' repository. If there are non-required params in the docs, but required in the client (this one), then it is not our fault.

**Comment by moltar** [comment]
Also, when discussing calls, please provide your exact code that you were using to help us help you better. Thanks :)

**Comment by jesusvalle** [comment]
I wasn't questioning whose fault it was, just that I haven't managed to get the sandbox working yet. I didn't provide the code because it was the same case I copied a couple of posts above, only excluding the params, sorry.

So no one else has the sandbox working for now?

**Comment by moltar** [comment]
Sandbox works but intermittently. It's pretty unreliable tbh.

**Comment by moltar** [comment]
@nguyentoanit could we have issues, because of the API differences: https://github.com/amzn/selling-partner-api-docs/tree/main/references/catalog-items-api

There seems to be 2 versions:

 - `v0`
 - `2020-12-01`

I don't think we still have received any guidance as far as how to tell which versions have been deprecated.

Correct me if I am wrong, but our logic is to pick the first version?

So in that case, we might be using `v0` and it might be deprecated?

**Comment by moltar** [comment]
Right, I do see we are using `v0`:

https://github.com/ScaleLeap/selling-partner-api-sdk/blob/f01125a61bf2d95768700eb1088e51e1e5f2bb49/src/api-models/catalog-items-api-model/api.ts#L7

**Comment by moltar** [comment]
The docs though document the `2020-12-01` version:

https://github.com/amzn/selling-partner-api-docs/blob/f114b54ae99d432c5bc72c3202ac80f8050379f7/guides/en-US/use-case-guides/catalog-items-api-use-case-guide/catalog-items-use-case-guide_2020-12-01.md

So we need to switch that.

**Comment by moltar** [comment]
Open an issue with them: https://github.com/amzn/selling-partner-api-docs/issues/704

**Comment by nguyentoanit** [comment]
> The docs though document the `2020-12-01` version:
> 
> https://github.com/amzn/selling-partner-api-docs/blob/f114b54ae99d432c5bc72c3202ac80f8050379f7/guides/en-US/use-case-guides/catalog-items-api-use-case-guide/catalog-items-use-case-guide_2020-12-01.md
> 
> So we need to switch that.

We're using `v0` instead of `2020-12-01` because they put both available and preview version in same directory.
It has been provided to understand the changes that would be made to the API.
If the new version is available for use, they will remove the older version from the GitHub repository.

Ref: https://github.com/amzn/selling-partner-api-docs/issues/646#issuecomment-825232385

**Comment by moltar** [comment]
@nguyentoanit I think the logic should be as follows:

If there is just a single model file -> go ahead and generate it.

If there is more than 1 model file, then we need to read each one, and get the `info.version` value.

Then we sort them in the following order:

 - `v*` (all `v` prefixed go first, sorted by numeric suffix)
 - `YYYY-MM-DD` (all dates go last, sorted)

If the version matches `YYYY-MM-DD` _and_ is in the future, then we discard it.

Then out of that remaining array of models, we take the last member.

**Comment by moltar** [comment]
>  If the new version is available for use, they will remove the older version from the GitHub repository.

I don't think that is true.

Because markdown docs already talk about the `2020-12-01` version, yet `v0` was not removed.

**Comment by nguyentoanit** [comment]
We've supported all preview API versions. See: https://selling-partner-api-sdk.scaleleap.org/
